import aiosqlite
from pathlib import Path
DB=Path("data/bot.db")
async def connect():
    DB.parent.mkdir(parents=True,exist_ok=True)
    x=await aiosqlite.connect(DB); x.row_factory=aiosqlite.Row
    await x.execute("PRAGMA foreign_keys=ON"); return x
async def init_db():
    x=await connect()
    await x.executescript('''
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,telegram_id INTEGER UNIQUE,username TEXT,first_name TEXT,blocked INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS admins(telegram_id INTEGER PRIMARY KEY,role TEXT DEFAULT 'admin');
CREATE TABLE IF NOT EXISTS chapters(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT DEFAULT '',position INTEGER DEFAULT 0,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS lessons(id INTEGER PRIMARY KEY AUTOINCREMENT,chapter_id INTEGER REFERENCES chapters(id) ON DELETE CASCADE,title TEXT NOT NULL,description TEXT DEFAULT '',position INTEGER DEFAULT 0,video_file_id TEXT,duration INTEGER DEFAULT 0,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS quizzes(id INTEGER PRIMARY KEY AUTOINCREMENT,lesson_id INTEGER UNIQUE REFERENCES lessons(id) ON DELETE CASCADE,pass_percent INTEGER DEFAULT 70,time_limit INTEGER DEFAULT 180,cooldown INTEGER DEFAULT 600);
CREATE TABLE IF NOT EXISTS questions(id INTEGER PRIMARY KEY AUTOINCREMENT,quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE,text TEXT NOT NULL,position INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS options(id INTEGER PRIMARY KEY AUTOINCREMENT,question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE,text TEXT NOT NULL,is_correct INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS progress(user_id INTEGER,lesson_id INTEGER,video_done INTEGER DEFAULT 0,quiz_passed INTEGER DEFAULT 0,completed_at TEXT,PRIMARY KEY(user_id,lesson_id));
CREATE TABLE IF NOT EXISTS attempts(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,quiz_id INTEGER,score INTEGER,passed INTEGER,started_at TEXT,finished_at TEXT,retry_after TEXT);
CREATE TABLE IF NOT EXISTS channels(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,chat_id TEXT,link TEXT,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS tickets(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,status TEXT DEFAULT 'open',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ticket_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,ticket_id INTEGER,sender_id INTEGER,text TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);
CREATE TABLE IF NOT EXISTS logs(id INTEGER PRIMARY KEY AUTOINCREMENT,admin_id INTEGER,action TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
''')
    await x.commit(); await x.close()
